### ISSUE TITLE
Verify task to maintain parity between npm and bower package versions

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-heroku-tools#108]
so e.g. fails build if next-barriers is at v2 in bower and v3 in npm.

**Comment by matthew-andrews** [comment]
oh nice, good idea

**Comment by matthew-andrews** [comment]
this could be a generic thing.  check to see if any npm depenedencies match bower ones, and make sure they're at the same version

**Comment by matthew-andrews** [comment]
i think we were going to do this by just having normal dependencies. reopen if i'm mistaken

**Comment by wheresrhys** [comment]
But that still doesn't protect against e.g. next-express@9 in npm, but @10 in bower though, does it?

I've had this open in a tab for ages, will get on to it soon

**Comment by wheresrhys** [comment]
Don't really want to tackle this until/unless we have the same names server and client side i.e. wait until everything is `n-*`-ified
