### ISSUE TITLE
Linting errors: Caught in travis-ci/push, but not in /travis-ci/pr or locally

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/n-heroku-tools#136]
Example: https://github.com/Financial-Times/next-beacon-dashboard/pull/113
- Two builds of (practically) the same code.
- One passes, one fails.
- The failing one has a linting error.  
- Can't reproduce error locally by running `nbt verify --skip-layout-checks`
- Can't see anything in https://github.com/Financial-Times/next-build-tools/blob/master/tasks/verify.js that might explain it.
- Maybe it's due to some configuration in travis?

It's easy to fix the linting issue, but somewhat annoying not to catch it locally. 

Pass: https://travis-ci.org/Financial-Times/next-beacon-dashboard/builds/68174172
Fail: https://travis-ci.org/Financial-Times/next-beacon-dashboard/builds/68174077

**Comment by matthew-andrews** [comment]
i think i saw that too.  super weird.

**Comment by adambraimbridge** [comment]
Update: I just discovered that ```nbt verify --skip-layout-checks``` is working locally for me. That is, it's catching the linting errors. Still, odd.
