### ISSUE TITLE
Support deploy, scale, configure and other tasks for multiple versions

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-heroku-tools#142]
I just updated `scale` to always pick the primary version. I reckon this is the only place in nbt that explicitly does this kind of thing, but configure (and deploy?) should do so too (otherwise why this http://git.svc.ft.com:8080/projects/NEXT/repos/service-registry/browse/server/models/profiles.js#541).

Then further to this, if we genuinely want to support splitting traffic between two versions of an app nbt would need to accept parameters to enable deploying multiple versions e.g. `nbt configure --version 3`

**Comment by matthew-andrews** [comment]
don't think the primary version / other version stuff ever was made to work…… suspect might better just to remove that complexity from service registry cc @commuterjoy ?
