### ISSUE TITLE
Client side test scaffolding

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-heroku-tools#148]
It'd be nice if we could have a workflow aspiring to 'I broke something in production, so my next responsibility (after fixing it) is to write a test so no-one else can break it again'

A barrier to this for components and client side unit tests is that often the scaffolding to run them (karma et al) isn't already in place, so writing that one test can be onerous.

So I suggest nbt installs karma + plugins, provides a default karma.conf and a test runner task

**Comment by matthew-andrews** [comment]
yes the overhead of setting up image diffing and nightwatch tests is way too high.

**Comment by matthew-andrews** [comment]
i'll add something the doc
