### ISSUE TITLE
Expects a global nodemon to be installed

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/n-heroku-tools#254]
https://github.com/Financial-Times/next-build-tools/blob/master/tasks/run.js#L61

This threw me for a while. I'm not sure how to make it look in the current working directories node_modules folder, I imagine that would be the solution for this.

**Comment by matthew-andrews** [comment]
Sorry to be a pedant but it doesn't require nodemon to be globally installed — but it does require nodemon to be available on the users $PATH. I think probably we should just make it a dependency of NBT.
