### ISSUE TITLE
check dependencies' status

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-heroku-tools#351]
Could roll https://github.com/dylang/npm-check in as a non-failing build/dev step

**Comment by matthew-andrews** [comment]
andy n is working on something to do this at the moment over in n-makefile.

**Comment by andygnewman** [comment]
Yes, it's here https://github.com/Financial-Times/next-article/pull/1280

Whitesource is a tool that is being reviewed across all of the FT's tech stack. Will show at next dev huddle.
