### ISSUE TITLE
deploy-static exits silently when given a directory source

### ISSUE THREAD

**Issue by lucas42** [Financial-Times/n-heroku-tools#388]
If the source parameter of deploy-static is a single directory, nothing happens.

**Steps to reproduce:**
```
mkdir build
nht deploy-static build
```
(Also occurs if you put some stuff in the directory)
**Output:**
No text.  Exit code 0.

**Expected:**
Some indication of what just happened.

**Comment by matthew-andrews** [comment]
PRs welcome 🙈
