### ISSUE TITLE
Nodemon watches too much 👀

### ISSUE THREAD

**Issue by leggsimon** [Financial-Times/n-heroku-tools#432]
running `nht run` defaults to use nodemon to watch for changes, however really you only want it to watch certain files maybe. Any time I run a git command with it in the background it will restart the app even though I haven't changed any files.

**Comment by ironsidevsquincy** [comment]
you can put a `nodemon.json` file in the root to tell it what to watch - https://github.com/Financial-Times/next-front-page/blob/master/nodemon.json
