### ISSUE TITLE
Remove dependency on service registry from configure task

### ISSUE THREAD

**Issue by jamesnicholls** [Financial-Times/n-heroku-tools#539]
Is there any chance we could remove the dependency on the service registry from the configure task? I am working on a project ([enterprise-tools](https://github.com/Financial-Times/enterprise-tools)) where we would quite like to make use of n-gage v3 (and nht) but would need to write our own configuration script because the app is not listed in the service registry.

**Comment by sjparkinson** [comment]
> Is there any chance we could remove the dependency on the service registry from the configure task?

What would the configure task look like without depending on the registry?

And do your apps really need to use the configure task?

**Comment by jamesnicholls** [comment]
I may missed something (probably have) but the service registry is just used to get the vault path. Could this be passed in as an argument instead?

**Comment by taktran** [comment]
I'm guessing from [L20](https://github.com/Financial-Times/n-heroku-tools/blob/v8.0.0-beta.7/tasks/configure.js#L20), that getting from the service registry is there to ensure system codes can be changed without having to change how `nht configure` works. I don't really know if system codes ever change like this, and if so, we might be changing how builds are run as well? Or I may have missed something too?

Considering we are explicitly calling the [`n-gage` variable `VAULT_NAME`](https://github.com/Financial-Times/n-gage/tree/v3.0.0-beta.26#deployment-variables), would it be safe to just remove that service registry check? It could be something that is done before we take `nht` and `n-gage` out of the betas @quarterto ?

/cc @Financial-Times/etg

**Comment by quarterto** [comment]
this feels like a nontrivial change and i'd rather get the major versions out soon?
