### ISSUE TITLE
Heroku build error: `No review app build found`

### ISSUE THREAD

**Issue by taktran** [Financial-Times/n-heroku-tools#570]
You can get into a state where CircleCI says

```
...
57/60: No review app build found for app id 'aa9df29c-13bd-4bc8-bf5b-cdd1e6a9000b';, commit 'ebaa8ec827f94c0cef80091b406f4f3d4b6505e7'
58/60: No review app build found for app id 'aa9df29c-13bd-4bc8-bf5b-cdd1e6a9000b';, commit 'ebaa8ec827f94c0cef80091b406f4f3d4b6505e7'
59/60: No review app build found for app id 'aa9df29c-13bd-4bc8-bf5b-cdd1e6a9000b';, commit 'ebaa8ec827f94c0cef80091b406f4f3d4b6505e7'
60/60: No review app build found for app id 'aa9df29c-13bd-4bc8-bf5b-cdd1e6a9000b';, commit 'ebaa8ec827f94c0cef80091b406f4f3d4b6505e7'
No review app build found for app id 'aa9df29c-13bd-4bc8-bf5b-cdd1e6a9000b';, commit 'ebaa8ec827f94c0cef80091b406f4f3d4b6505e7'

 Error: No review app build found for app id 'aa9df29c-13bd-4bc8-bf5b-cdd1e6a9000b';, commit 'ebaa8ec827f94c0cef80091b406f4f3d4b6505e7'
    at getAppBuildWithCommit.then (/home/circleci/project/build/node_modules/@financial-times/n-heroku-tools/lib/review-apps.js:161:12)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
/home/circleci/project/build/node_modules/@financial-times/n-gage/src/tasks/review-app.mk:12: recipe for target '.review-app' failed
make[1]: *** [.review-app] Error 1
make[1]: *** Deleting file '.review-app'
make[1]: Leaving directory '/home/circleci/project/build'
/home/circleci/project/build/node_modules/@financial-times/n-gage/src/tasks/review-app.mk:36: recipe for target 'test-review-app' failed
make: *** [test-review-app] Error 2
Exited with code 2
```

Even though it worked the day before eg, https://circleci.com/gh/Financial-Times/next-product/6208

Deleting the Heroku app, and rerunning the build fixes the issue.

It appears that Heroku has deleted the app for some reason. This is weird because

* `Destroy stale review apps automatically` is set to 2 days.
* We do check for deleted review apps here: https://github.com/Financial-Times/n-heroku-tools/blob/56f89c1c2093e3d9f564b79d7fd2c20068093391/lib/review-apps.js#L70

Need to try and replicate and check what the REST endpoints have.

**Comment by taktran** [comment]
This can happen when you force push a commit, as the git sha we are looking for is out of date.

Example of bug:

https://circleci.com/gh/Financial-Times/next-es-interface/7147

![Screenshot 2019-06-21 at 10 40 09 am](https://user-images.githubusercontent.com/79451/59913911-15a4fd80-9411-11e9-9502-c9cc3be7fb4c.png)

The first `provision` passes, but then on the force commit, `provision` fails, and the circleci logs say

> Review app already created for 'bugs/default-caption-style' branch. Using existing review app for build.

----

We could either:

* Do something a bit smarter when checking the git sha/branch
* Brute force fix: retry `provision` by first deleting the review app, and trying again

**Comment by adambraimbridge** [comment]
I hit this issue today. Thanks @taktran 🤗 

https://app.circleci.com/jobs/github/Financial-Times/next-control-centre/3997

**Comment by andygout** [comment]
Fixed by https://github.com/Financial-Times/n-heroku-tools/pull/605
